apiVersion: v1
kind: Service
metadata:
  name: jiradata-api-service
  namespace: default
  labels:
    app: jiradata-api
spec:
  type: LoadBalancer
  selector:
    app: jiradata-api
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP

